### PR TITLE
chore: remove points metric

### PR DESCRIPTION
**Pull request by kirillovzah**

### CODE REVIEW

**Comment by dryabinin-actionengine** [comment]
I am not sure about removing this metric on application level. @belom88 What do you think?
Instead we can check what is the type of tileset and enable Point metric for PointCloud tileset only.
You can see it here - https://github.com/visgl/loaders.gl/blob/master/modules/tiles/src/tileset/tileset-3d.ts#L575-L589

Also to verify your changes do:

1. Clone `loaders.gl` repo next to your `loaders-gl-showcases `repo
2. cd loaders.gl 
3. yarn bootstrap
4. cd loaders.gl-showcases
5. yarn
6. yarn start-local-loaders
After these commands all loaders.gl local changes will be applied in real time and will be picked up by loaders.gl-showcases project.

**Comment by ibgreen** [comment]
For non-points, counting vertices is often a good way to measure the size of the geometry...

**Comment by belom88** [comment]
> For non-points, counting vertices is often a good way to measure the size of the geometry...

@kirillovzah is it always 0 for I3S. We could increment vertex count in the "Points" metric when geometry is loaded.

**Comment by dryabinin-actionengine** [comment]
I close this PR, because we added vertex metric for non point cloud tilesets https://github.com/visgl/loaders.gl/pull/2163)

**Pull request closed without merging**
